name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev \
          build-essential ccache libncursesw5-dev libsqlite3-dev tk-dev \
          libgdbm-dev libc6-dev libbz2-dev libreadline-dev
    
    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33
        pip install kivy[base] kivymd plyer
    
    - name: Cache Buildozer dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
      env:
        ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: rftx-tuning-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
